#version: "3.8"

services:
  foundry:
    container_name: foundry
    image: ghcr.io/foundry-rs/foundry:stable
    platform: linux/amd64 
    entrypoint: anvil --block-time 1 --block-base-fee-per-gas 0 --gas-limit 3000000000 --hardfork cancun --host 0.0.0.0 --port 8546
    ports:
      - "8546:8546"
    healthcheck:
      test: ["CMD-SHELL", "anvil --help || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  world-deployer:
    container_name: world-deployer
    image: ghcr.io/projectawakening/world-chain-deployer-image:latest
    platform: linux/amd64
    volumes:
      - ./logs:/monorepo/logs  # Maps host ./logs to container /monorepo/logs
    depends_on:
      foundry:
        condition: service_healthy
    env_file:
      - .env
    command: "deploy-v2  --rpc-url http://foundry:8546 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    tty: true
