// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { BucketedInventoryItem, BucketedInventoryItemData } from "./tables/BucketedInventoryItem.sol";
import { BucketMetadata, BucketMetadataData } from "./tables/BucketMetadata.sol";
import { BucketConfig } from "./tables/BucketConfig.sol";
import { InventoryBalances, InventoryBalancesData } from "./tables/InventoryBalances.sol";
import { BucketOwners, BucketOwnersData } from "./tables/BucketOwners.sol";
import { BucketInventory, BucketInventoryData } from "./tables/BucketInventory.sol";
