// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { BucketSystem } from "../../systems/StorageSystem/BucketSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type BucketSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "sm_v0_2_0", name: "BucketSystem" }))
BucketSystemType constant bucketSystem = BucketSystemType.wrap(
  0x7379736d5f76305f325f3000000000004275636b657453797374656d00000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title BucketSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library BucketSystemLib {
  error BucketSystemLib_CallingFromRootSystem();

  function getCreateSystemAddress(BucketSystemType self) internal view returns (address) {
    return CallWrapper(self.toResourceId(), address(0)).getCreateSystemAddress();
  }

  function createNestedBuckets(
    BucketSystemType self,
    uint256 smartObjectId,
    string memory bucketName
  ) internal returns (bytes32[] memory) {
    return CallWrapper(self.toResourceId(), address(0)).createNestedBuckets(smartObjectId, bucketName);
  }

  function transferBucketToParent(
    BucketSystemType self,
    uint256 smartObjectId,
    bytes32 bucketId,
    bytes32 newParentBucketId
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).transferBucketToParent(smartObjectId, bucketId, newParentBucketId);
  }

  function getCreateSystemAddress(CallWrapper memory self) internal view returns (address) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert BucketSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_getCreateSystemAddress.getCreateSystemAddress, ());
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    return abi.decode(result, (address));
  }

  function createNestedBuckets(
    CallWrapper memory self,
    uint256 smartObjectId,
    string memory bucketName
  ) internal returns (bytes32[] memory) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert BucketSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createNestedBuckets_uint256_string.createNestedBuckets,
      (smartObjectId, bucketName)
    );

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    return abi.decode(result, (bytes32[]));
  }

  function transferBucketToParent(
    CallWrapper memory self,
    uint256 smartObjectId,
    bytes32 bucketId,
    bytes32 newParentBucketId
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert BucketSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _transferBucketToParent_uint256_bytes32_bytes32.transferBucketToParent,
      (smartObjectId, bucketId, newParentBucketId)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function getCreateSystemAddress(RootCallWrapper memory self) internal view returns (address) {
    bytes memory systemCall = abi.encodeCall(_getCreateSystemAddress.getCreateSystemAddress, ());

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    return abi.decode(result, (address));
  }

  function createNestedBuckets(
    RootCallWrapper memory self,
    uint256 smartObjectId,
    string memory bucketName
  ) internal returns (bytes32[] memory) {
    bytes memory systemCall = abi.encodeCall(
      _createNestedBuckets_uint256_string.createNestedBuckets,
      (smartObjectId, bucketName)
    );

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    return abi.decode(result, (bytes32[]));
  }

  function transferBucketToParent(
    RootCallWrapper memory self,
    uint256 smartObjectId,
    bytes32 bucketId,
    bytes32 newParentBucketId
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _transferBucketToParent_uint256_bytes32_bytes32.transferBucketToParent,
      (smartObjectId, bucketId, newParentBucketId)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(BucketSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(BucketSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), msg.sender);
  }

  function callAsRootFrom(BucketSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(BucketSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(BucketSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (BucketSystemType) {
    return BucketSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(BucketSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _getCreateSystemAddress {
  function getCreateSystemAddress() external;
}

interface _createNestedBuckets_uint256_string {
  function createNestedBuckets(uint256 smartObjectId, string memory bucketName) external;
}

interface _transferBucketToParent_uint256_bytes32_bytes32 {
  function transferBucketToParent(uint256 smartObjectId, bytes32 bucketId, bytes32 newParentBucketId) external;
}

using BucketSystemLib for BucketSystemType global;
using BucketSystemLib for CallWrapper global;
using BucketSystemLib for RootCallWrapper global;
