// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { StorageSystem } from "../../systems/StorageSystem/StorageSystem.sol";
import { InventoryItemParams } from "@eveworld/world-v2/src/namespaces/evefrontier/systems/inventory/types.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type StorageSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "sm_v0_2_0", name: "StorageSystem" }))
StorageSystemType constant storageSystem = StorageSystemType.wrap(
  0x7379736d5f76305f325f30000000000053746f7261676553797374656d000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title StorageSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library StorageSystemLib {
  error StorageSystemLib_CallingFromRootSystem();

  function getSystemAddress(StorageSystemType self) internal view returns (address) {
    return CallWrapper(self.toResourceId(), address(0)).getSystemAddress();
  }

  function deposit(
    StorageSystemType self,
    uint256 smartObjectId,
    bytes32 bucketId,
    bool useOwnerInventory,
    InventoryItemParams[] memory transferItems
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).deposit(smartObjectId, bucketId, useOwnerInventory, transferItems);
  }

  function withdraw(
    StorageSystemType self,
    uint256 smartObjectId,
    bytes32 bucketId,
    bool useOwnerInventory,
    InventoryItemParams[] memory transferItems
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).withdraw(smartObjectId, bucketId, useOwnerInventory, transferItems);
  }

  function internalTransfer(
    StorageSystemType self,
    uint256 smartObjectId,
    bytes32 sourceBucketId,
    bytes32 recipientBucketId,
    InventoryItemParams[] memory transferItems
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).internalTransfer(
        smartObjectId,
        sourceBucketId,
        recipientBucketId,
        transferItems
      );
  }

  function getSystemAddress(CallWrapper memory self) internal view returns (address) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert StorageSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_getSystemAddress.getSystemAddress, ());
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    return abi.decode(result, (address));
  }

  function deposit(
    CallWrapper memory self,
    uint256 smartObjectId,
    bytes32 bucketId,
    bool useOwnerInventory,
    InventoryItemParams[] memory transferItems
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert StorageSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _deposit_uint256_bytes32_bool_InventoryItemParamsArray.deposit,
      (smartObjectId, bucketId, useOwnerInventory, transferItems)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function withdraw(
    CallWrapper memory self,
    uint256 smartObjectId,
    bytes32 bucketId,
    bool useOwnerInventory,
    InventoryItemParams[] memory transferItems
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert StorageSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _withdraw_uint256_bytes32_bool_InventoryItemParamsArray.withdraw,
      (smartObjectId, bucketId, useOwnerInventory, transferItems)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function internalTransfer(
    CallWrapper memory self,
    uint256 smartObjectId,
    bytes32 sourceBucketId,
    bytes32 recipientBucketId,
    InventoryItemParams[] memory transferItems
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert StorageSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _internalTransfer_uint256_bytes32_bytes32_InventoryItemParamsArray.internalTransfer,
      (smartObjectId, sourceBucketId, recipientBucketId, transferItems)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function getSystemAddress(RootCallWrapper memory self) internal view returns (address) {
    bytes memory systemCall = abi.encodeCall(_getSystemAddress.getSystemAddress, ());

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    return abi.decode(result, (address));
  }

  function deposit(
    RootCallWrapper memory self,
    uint256 smartObjectId,
    bytes32 bucketId,
    bool useOwnerInventory,
    InventoryItemParams[] memory transferItems
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _deposit_uint256_bytes32_bool_InventoryItemParamsArray.deposit,
      (smartObjectId, bucketId, useOwnerInventory, transferItems)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function withdraw(
    RootCallWrapper memory self,
    uint256 smartObjectId,
    bytes32 bucketId,
    bool useOwnerInventory,
    InventoryItemParams[] memory transferItems
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _withdraw_uint256_bytes32_bool_InventoryItemParamsArray.withdraw,
      (smartObjectId, bucketId, useOwnerInventory, transferItems)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function internalTransfer(
    RootCallWrapper memory self,
    uint256 smartObjectId,
    bytes32 sourceBucketId,
    bytes32 recipientBucketId,
    InventoryItemParams[] memory transferItems
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _internalTransfer_uint256_bytes32_bytes32_InventoryItemParamsArray.internalTransfer,
      (smartObjectId, sourceBucketId, recipientBucketId, transferItems)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(StorageSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(StorageSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), msg.sender);
  }

  function callAsRootFrom(StorageSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(StorageSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(StorageSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (StorageSystemType) {
    return StorageSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(StorageSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _getSystemAddress {
  function getSystemAddress() external;
}

interface _deposit_uint256_bytes32_bool_InventoryItemParamsArray {
  function deposit(
    uint256 smartObjectId,
    bytes32 bucketId,
    bool useOwnerInventory,
    InventoryItemParams[] memory transferItems
  ) external;
}

interface _withdraw_uint256_bytes32_bool_InventoryItemParamsArray {
  function withdraw(
    uint256 smartObjectId,
    bytes32 bucketId,
    bool useOwnerInventory,
    InventoryItemParams[] memory transferItems
  ) external;
}

interface _internalTransfer_uint256_bytes32_bytes32_InventoryItemParamsArray {
  function internalTransfer(
    uint256 smartObjectId,
    bytes32 sourceBucketId,
    bytes32 recipientBucketId,
    InventoryItemParams[] memory transferItems
  ) external;
}

using StorageSystemLib for StorageSystemType global;
using StorageSystemLib for CallWrapper global;
using StorageSystemLib for RootCallWrapper global;
