// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAccessUtilsSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAccessUtilsSystem {
  function sm_v0_2_0__hasRoles(bytes32[] memory roleIds, address account) external view returns (bool[] memory);

  function sm_v0_2_0__getOwnersOf(uint256[] memory smartObjectIds) external view returns (address[] memory);
}
