// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBucketSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBucketSystem {
  function sm_v0_2_0__getCreateSystemAddress() external view returns (address);

  function sm_v0_2_0__createNestedBuckets(
    uint256 smartObjectId,
    string memory bucketName
  ) external returns (bytes32[] memory);

  function sm_v0_2_0__transferBucketToParent(
    uint256 smartObjectId,
    bytes32 bucketId,
    bytes32 newParentBucketId
  ) external;
}
