// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { InventoryItemParams } from "@eveworld/world-v2/src/namespaces/evefrontier/systems/inventory/types.sol";

/**
 * @title IStorageSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IStorageSystem {
  function sm_v0_2_0__getSystemAddress() external view returns (address);

  function sm_v0_2_0__deposit(
    uint256 smartObjectId,
    bytes32 bucketId,
    bool useOwnerInventory,
    InventoryItemParams[] memory transferItems
  ) external;

  function sm_v0_2_0__withdraw(
    uint256 smartObjectId,
    bytes32 bucketId,
    bool useOwnerInventory,
    InventoryItemParams[] memory transferItems
  ) external;

  function sm_v0_2_0__internalTransfer(
    uint256 smartObjectId,
    bytes32 sourceBucketId,
    bytes32 recipientBucketId,
    InventoryItemParams[] memory transferItems
  ) external;
}
