// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { InventoryItemParams } from "@eveworld/world-v2/src/namespaces/evefrontier/systems/inventory/types.sol";

/**
 * @title IStoreLogicSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IStoreLogicSystem {
  function sm_v0_2_0___processDeposit(
    uint256 smartObjectId,
    bytes32 bucketId,
    InventoryItemParams memory item
  ) external;

  function sm_v0_2_0___processWithdraw(
    uint256 smartObjectId,
    bytes32 bucketId,
    InventoryItemParams memory item
  ) external;

  function sm_v0_2_0___processAggBucketsBalance(
    uint256 smartObjectId,
    bytes32 bucketId,
    bool isWithdrawal,
    InventoryItemParams memory item
  ) external;
}
