// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { InventoryItemParams } from "@eveworld/world-v2/src/namespaces/evefrontier/systems/inventory/types.sol";

/**
 * @title IStoreProxySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IStoreProxySystem {
  function sm_v0_2_0__getStoreProxyAddress() external view returns (address);

  function sm_v0_2_0__proxyTransferToEphemeral(
    uint256 smartObjectId,
    address recipient,
    InventoryItemParams[] memory transferItems
  ) external;

  function sm_v0_2_0__proxyTransferFromEphemeral(
    uint256 smartObjectId,
    address sender,
    InventoryItemParams[] memory transferItems
  ) external;

  function sm_v0_2_0__proxyCrossTransferToEphemeral(
    uint256 smartObjectId,
    address fromEphemeralOwner,
    address toEphemeralOwner,
    InventoryItemParams[] memory items
  ) external;

  function sm_v0_2_0__proxyTransferToInventory(
    uint256 smartObjectId,
    uint256 toObjectId,
    InventoryItemParams[] memory items
  ) external;
}
