// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

/**
 * @title IStoreAuthSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IStoreAuthSystem {
  function sm_v0_2_0__setAccessSystemId(uint256 smartObjectId, bytes32 bucketId, ResourceId systemId) external;

  function sm_v0_2_0__getCharacterTribeByAddress(address playerAddress) external view returns (uint256);

  function sm_v0_2_0__fetchAuthorizationSystemId(
    uint256 smartObjectId,
    bytes32 bucketId
  ) external view returns (ResourceId);

  function sm_v0_2_0__canDeposit(uint256 smartObjectId, bytes32 bucketId, address sender) external returns (bool);

  function sm_v0_2_0__canWithdraw(uint256 smartObjectId, bytes32 bucketId, address sender) external returns (bool);

  function sm_v0_2_0__canTransferBucket(
    uint256 smartObjectId,
    bytes32 bucketId,
    address sender
  ) external returns (bool);
}
