// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";
import { IAccessUtilsSystem } from "./IAccessUtilsSystem.sol";
import { ISmUtilsSystem } from "./ISmUtilsSystem.sol";
import { IBucketSystem } from "./IBucketSystem.sol";
import { IStorageSystem } from "./IStorageSystem.sol";
import { IStoreAuthSystem } from "./IStoreAuthSystem.sol";
import { IStoreLogicSystem } from "./IStoreLogicSystem.sol";
import { IStoreProxySystem } from "./IStoreProxySystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IAccessUtilsSystem,
  ISmUtilsSystem,
  IBucketSystem,
  IStorageSystem,
  IStoreAuthSystem,
  IStoreLogicSystem,
  IStoreProxySystem
{}
