[profile.default]
solc = "0.8.24"
evm_version = "cancun"
ffi = false
fuzz_runs = 256
optimizer_runs = 3000
verbosity = 2
src = "src"
test = "test"
out = "out"
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
  # template uses linked mud packages from within the mud monorepo
  "../../../../packages",
  # projects created from this template and using linked mud packages
  "../../../mud/packages",
  "./node_modules"
]
extra_output_files = ["abi", "evm.bytecode"]
fs_permissions = [{ access = "read", path = "./" }]
script_execution_protection=false
cache=true
allow_internal_expect_revert = true
optimizer = false
viaIR = true

[profile.local]
# Local Devnet
eth_rpc_url = "http://127.0.0.1:8546"
optimizer = false
viaIR = true

[profile.redstone]
# Public Mainnet
eth_rpc_url = "https://rpc.redstonechain.com"

[profile.pyrope]
# Current Testnet
eth_rpc_url = "https://pyrope-external-sync-node-rpc.live.tech.evefrontier.com"
viaIR = true
optimizer = true